Renderui
FuadBalashov/Spinder pull request #2
Opened 2017-02-27 23:40 UTC by RPrather27

Second Commit Only

2017-02-28 01:38 UTC, RPrather27 commented
@FuadBalashov Ready for code Review!

2017-02-28 12:58 UTC, FuadBalashov requested changes
Some changes I'd like to see, make sure to turn on your linter!

We should rethink our approach of just throwing everything (including transition handling) inside of the entry point. We can discuss that in planning.

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +            {`LOOK! IT'S ${prefferedName}. Could be the one!`}
looks like we aren't defining `preferredName` (misspelling on the variable too).

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
>      const { firstName, lastName, picture, blurb } = ProfileData.retrieve(matchId);
please remove firstName and lastName if they aren't being used anymore

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +      return validMatchRankings.get(0)
#codestyle
Use semicolons at the end of lines

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +          <Spinder mode='picker' triggerMatch={() => this.onSpinEvent}/>
is this supposed to be the spinner component?

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +          <Spinder mode='picker' triggerMatch={() => this.onSpinEvent}/>
don't use anonymous functions or lambdas as listeners. Instead just pass triggerMatch this.onSpinEvent:
````
triggerMatch={this.onSpinEvent}
````

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +      return (
I few have the messenger logic here we should consider creating new components to hold the logic for hosting the spinner and the messenger. We should discuss this next time in planning.

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +            <Spinder mode='initial' beginMatching={() => this.onSpinEvent}/>
no annon functions as props

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +    const reciepientResponce = ProfileData.sendMatchLevel(this.props.username, currentMatch, matchLevel);
misspelling?

2017-02-28 12:58 UTC, FuadBalashov commented on entry-points/spin-entry-point.js
> +            {'But they say it takes' + {previousHits + 1} + ' tries to find love!'}
add a space after `takes`

2017-02-28 12:58 UTC, FuadBalashov commented on components/Spinner.js
> +    if (accelLevel > 9000) {
While this seems obvious to me it may not be clear why we picked 9k for everyone. Could you add comment explaining this cut-off?

2017-02-28 16:40 UTC, FuadBalashov approved these changes
LGTM!

2017-03-01 15:21 UTC, DanniRiggin commented
This is a QE pass. See JIRA ticket for comments.

2017-03-01 17:51 UTC, kevin-hogan requested changes
The acceleration threshold must be totally off. It's wayy to sensitive to rotations. @RPrather27 Let's chat in person.

2017-03-01 18:11 UTC, kevin-hogan approved these changes

2017-03-01 18:19 UTC, merged